language: python

sudo: false

install:
  - pip install codecov
  - pip install flake8

script:
  - coverage run tests.py && coverage xml -o coverage_A.xml && codecov -t "0a5a6692-f82f-4aa0-a3aa-1cde10c13de3" -f coverage_A.xml
  - coverage run test2.py && coverage xml -o coverage_B.xml && codecov -t "0a5a6692-f82f-4aa0-a3aa-1cde10c13de3" -f coverage_B.xml -F projectb


deploy:
  provider: pages
  skip_cleanup: true
  github_token: 'b661bbaf4b49ffaabd78f2ad476dd3898729075e' # Set in travis-ci.org dashboard
  on:
    branch: master
    all_branches: true
